In [2]:
from __future__ import print_function
import torch

In [12]:
x = torch.Tensor(5, 3)
x


1.00000e-02 *
  0.0014  0.0000  0.0014
  0.0000  0.0000  0.0000
  0.0000  0.0000  0.0000
  0.0000  0.0000  0.0000
  0.0000  6.7079  0.0000
[torch.FloatTensor of size 5x3]

In [11]:
x = torch.Tensor(5, 3)
x


1.00000e-05 *
  1.4461  0.0000  1.4461
  0.0000  0.0000  0.0000
  0.0000  0.0000  0.0000
  0.0000  0.0000  0.0000
  0.0000  0.0000  0.0000
[torch.FloatTensor of size 5x3]

In [15]:
x.size()

torch.Size([5, 3])

In [16]:
y = torch.rand(5, 3)
x + y


 0.7430  0.8147  0.7218
 0.2855  0.4403  0.0533
 0.8230  0.7849  0.7312
 0.8969  0.1623  0.3064
 0.9337  0.1418  0.7265
[torch.FloatTensor of size 5x3]

In [17]:
torch.add(x, y)


 0.7430  0.8147  0.7218
 0.2855  0.4403  0.0533
 0.8230  0.7849  0.7312
 0.8969  0.1623  0.3064
 0.9337  0.1418  0.7265
[torch.FloatTensor of size 5x3]

In [19]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
result


 0.7430  0.8147  0.7218
 0.2855  0.4403  0.0533
 0.8230  0.7849  0.7312
 0.8969  0.1623  0.3064
 0.9337  0.1418  0.7265
[torch.FloatTensor of size 5x3]

In [20]:
# adds x to y
y.add_(x)
y


 0.7430  0.8147  0.7218
 0.2855  0.4403  0.0533
 0.8230  0.7849  0.7312
 0.8969  0.1623  0.3064
 0.9337  0.1418  0.7265
[torch.FloatTensor of size 5x3]

- Note

Any operation that mutates a tensor in-place is post-fixed with an _ For example: x.copy_(y), x.t_(), will change x.

In [21]:
x[:, 1]


1.00000e-02 *
  0.0000
  0.0000
  0.0000
  0.0000
  6.7079
[torch.FloatTensor of size 5]

In [22]:
a = torch.ones(5)
a


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]

In [23]:
b = a.numpy()
b

array([ 1.,  1.,  1.,  1.,  1.], dtype=float32)

In [24]:
# how the numpy array changed in value.
a.add_(1)
print(a)
print(b)


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

[ 2.  2.  2.  2.  2.]


In [26]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[ 2.  2.  2.  2.  2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]



In [31]:
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    x + y